# Imagem de referencia do Locust para ser usada como Job/Deployment no K8s.
# O aluno deve trocar para Wolfi/Distroless se quiser manter o padrao do Day-13.
FROM locustio/locust:2.31.3
COPY locustfile.py /mnt/locust/locustfile.py
