apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: tipsbank-contas
type: Opaque
stringData:
  POSTGRES_USER: tipsbank
  POSTGRES_PASSWORD: giropops
  POSTGRES_DB: tipsbank
  DATABASE_URL: postgresql+psycopg://tipsbank:giropops@postgres.tipsbank-contas.svc.cluster.local:5432/tipsbank
